/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cloud_logic_custom": [
        {
            "name": "api3b1d7fc7",
            "endpoint": "https://inlgjflikf.execute-api.eu-west-3.amazonaws.com/dev",
            "region": "eu-west-3"
        }
    ]
};


export default awsmobile;
